### ISSUE TITLE
◇ 英国墙友收录的当前世界墙农的把戏

### ISSUE THREAD

**Issue by jasonliul** [phuslu/gop#1895]
◇ 英国墙友收录的当前世界墙农的把戏

**致谢英国墙友0bin**

Current methods

The system blocks content by preventing IP addresses from being routed through. It consists of standard firewalls and proxy servers at the Internet gateways. The system also selectively engages in DNS poisoning when particular sites are requested. The government does not appear to be systematically examining Internet content, as this seems to be technically impractical.[48] Researchers at the University of California, Davis, and at the University of New Mexico said that the censorship system is not a true firewall since banned material is sometimes able to pass through several routers or through the entire system without being blocked.[32] Details for some commonly used technical methods for censoring are:[49]

Method	Description

IP blocking
	
The access to a certain IP address is denied. If the target Web site is hosted in a shared hosting server, all Web sites on the same server will be blocked. This affects all IP protocols (mostly TCP) such as HTTP, FTP or POP. A typical circumvention method is to find proxies that have access to the target Web sites, but proxies may be jammed or blocked. Some large Web sites allocated additional IP addresses (for instance, an IPv6 address) to circumvent the block, but later the block may be extended to cover the new addresses.[citation needed]

DNS filtering and redirection	

The DNS doesn't resolve domain names or returns incorrect IP addresses.[50] This affects all IP protocols such as HTTP, FTP or POP. A typical circumvention method is to find a domain name server that resolves domain names correctly, but domain name servers are subject to blockage as well, especially IP blocking. Another workaround is to bypass DNS if the IP address is obtainable from other sources and is not blocked. Examples are modifying the Hosts file or typing the IP address instead of the domain name in a Web browser.

URL filtering	

Scan the requested Uniform Resource Locator (URL) string for target keywords regardless of the domain name specified in the URL. This affects the Hypertext Transfer Protocol. Typical circumvention methods are to use escaped characters in the URL, or to use encrypted protocols such as VPN and SSL.[51]

Packet filtering	

Terminate TCP packet transmissions when a certain number of controversial keywords are detected. This can be effective with many TCP protocols such as HTTP, FTP or POP, but web search engine pages are more likely to be censored. Typical circumvention methods are to use encryption means, such as VPN and SSL, to protect the HTML content, or reducing the TCP/IP stack's MTU, thus reducing the amount of text contained in a given packet.

Man-in-the-middle attack	

GFW can use a root certificate from CNNIC, which is found in most operating systems and browsers, to make a MITM attack. On 26 Jan 2013, the GitHub SSL certificate was replaced with a self-signed certificate in China by, generally believed, the GFW.[52]

TCP connection reset	

If a previous TCP connection is blocked by the filter, future connection attempts from both sides will also be blocked for up to 30 minutes. Depending on the location of the block, other users or Web sites may be also blocked if the communications are routed to the location of the block. A circumvention method is to ignore the reset packet sent by the firewall.[53]

VPN blocking	

Beginning in 2011, users reported disruptions of Virtual Private Network (VPN) services.[54] In late 2012, the Great Firewall was able to "learn, discover and block" the encrypted communications methods used by a number of different VPN systems. China Unicom, one of the biggest telecoms providers in the country was terminating connections where a VPN is detected, according to one company with a number of users in China.[55]

Other reported methods have included:
Method	Description

Network enumeration	

It has been reported that unknown entities within China, likely with deep packet inspection (DPI) capabilities, have initiated unsolicited TCP/IP connections to computers within the United States for the purported purpose of network enumeration of services, in particular TLS/SSL and Tor (anonymity network) services, with the aim of facilitating IP blocking.[56]

https://en.wikipedia.org/wiki/Golden_Shield_Project
https://en.wikipedia.org/wiki/Internet_censorship_in_China#Evasion

    China Digital Times: Internet Control
http://chinadigitaltimes.net/tag/Internet-control
    Breaking Through the "Golden Shield"
http://www.soros.org/resources/articles_publications/articles/china-internet-censorship-20041101
    ViewDNS.info - Chinese Firewall Test - Tests if Golden Shield is performing DNS filtering/redirection on your domain within mainland China.
http://www.viewdns.info/chinesefirewall/
    Great Firewall Test- Tests if a website (or third-party hosts to a website) is filtered from within Great Firewall of China using an actual Internet Explorer browser
https://www.vpnmentor.com/test-the-great-china-firewall/
    Website Test behind the Great Firewall of China
http://www.websitepulse.com/help/testtools.china-test.html

**Comment by tec1987** [comment]
有能力的还是争取早日肉翻吧。。。

**Comment by jasonliul** [comment]
@tec1987 
2015年春, 瓦伦西亚世界墙民节, 年底欧人的世界墙国图发布, 筑墙的国家越来越多...
你想翻一堵又一堵? :)

**Comment by tec1987** [comment]
都跟PRC学坏了。。。

**Comment by jasonliul** [comment]
筑墙的目的是为利益, 不是那些粪青叫嚣的伪政治...
百毒代替谷歌, 优酷代替y2b... 其中的利益很露骨.

中国谷歌幸存是因为谷歌的广告合作政策, 那些钱不归谷歌.

**Comment by jasonliul** [comment]
从2015年开始, 唯一世界墙民的利好是:
July 12th: Internet-Wide Day of Action to Save Net Neutrality
The FCC wants to destroy net neutrality and give big cable companies control over what we see and do online. If they get their way, they’ll allow widespread throttling, blocking, censorship, and extra fees. On July 12th, the Internet will come together to stop them.

中国墙民大概是某种异形...

2015年, 等于筑墙, 跳墙的都结盟, 加上7.12商家加入PK, 是近几年世界墙民三大事件.
中国人几乎就是旁观者~~

**Comment by blob2015** [comment]
胡乱侃几句。当是下酒小菜。
世界形势，目前相当相当相当“微妙”。
欧洲相当危险，可能全面绿化。非洲人口大爆发，高的，能达到5【2为平衡】。亚洲有一定体量的，人口增长第一的，是菲律宾【想不到吧 😀 】，像李家坡，好像只有0.8 😀 
美国佬的无底洞，不知道什么时候爆发……老大、老二是等着看谁先死……都亚历山大……
最近比较危险的，可能成为攻击目标的，据说有两，一个是阿三，一个是印尼……因为已经有人饥饿难耐……
拉美，毒品，社会固化，腐败，治安一塌糊涂……
中东，这个不用说了吧？
肉翻，翻到那里去？给个目标？ 😀

**Comment by tec1987** [comment]
澳洲不错 :grinning:

**Comment by hcym** [comment]
智力不够，好地方多了去了，就怕你腿不够用钱不够多
不上新闻头版的都是好地方

**Comment by blob2015** [comment]
只要你一人爽，去拿都行，反正最多也就熬个60年，是吧
你孩子管不管？不管孩子也行，那你倒是举例啊，别跟我说什么太平洋岛国，风景胜地啊

---------------------------

@tec1987 
澳洲与加拿大勉强算两个

**Comment by hcym** [comment]
基督教的应许之地，就是一家老小生活的地方
不讨厌gfw，中国就有很多
外国更是海海阔阔天天空空

**Comment by blob2015** [comment]
😀 😀 😀 
你在中东？高人啊
我们在讲肉翻……然后又一通说什么智力……
老兄直接来个中国就有很多……真是智力……
“外国更是海海阔阔天天空空”，别说你连香港都没到过啊……
一会儿看破世界的尘埃，随遇而安，一会儿又赞美主，一会儿又外国更是海阔天空，这跳跃，真是……
行了，先到此为止啦，本来也就说了，下酒小菜，活跃下气氛，捧个场罢了 😀
