### ISSUE TITLE
社长的猜测, 答案:正确

### ISSUE THREAD

**Issue by jasonliul** [phuslu/gop#1904]
多手仔反复重启路由器, 俺终于回到未封线路.

奇妙的就是, 之前quic那些千军万马的ip, 现在少得可怜...
即使加上#1903那些历史IP.

看来社长猜测英明, 墙农们是开开关关的游戏~~

**Comment by tec1987** [comment]
你那能用TCP了？

**Comment by phuslu** [comment]
嗯嗯，
> 蜗牛角上争名利，石火光中寄此身。

用的一天是一天罢。

**Comment by jasonliul** [comment]
俺这里通常分配3种字头的ip, 现在这种很少见, 估计是坟场火葬场那边调拨的线路...
且爽一下, 等会有人嫌慢, 又会重启~~~
:)

**Comment by hcym** [comment]
社长是十年怕井绳子

**Comment by tec1987** [comment]
现在运营商的家用线路大多都是动态分配的，本地资源有限的话，可能会给你分配异地出口。。。
某个国际出口拥堵的话，可能会走其它出口。。。

有时候连接某个网站连不上，重启路由或者重拨号换个IP就好了。。。
