### ISSUE TITLE
这里聚会

### ISSUE THREAD

**Issue by candy2107** [phuslu/gop#1911]
https://gitter.im/goproxy_talk/goproxy
换个地方可好？
如果社长认为大家在自家项目讨论威胁到自己的安全，我等深表歉意。

**Comment by phuslu** [comment]
其实有个 https://gitter.im/phuslu/goproxy

**Comment by THLIVSQAZ** [comment]
好高兴，重开了

**Comment by candy2107** [comment]
@phuslu 
能否换个github账号继续项目
这个gop项目在您的popular repositories 显示了 迟早会被发现

**Comment by phuslu** [comment]
谢谢提醒，我改了改，现在不显示了。
