### ISSUE TITLE
vps server端域名大小写问题

### ISSUE THREAD

**Issue by yoker** [phuslu/gop#1916]
@phuslu 服务端生成了`abc.xx.com`/`Abc.xx.com`/`ABC.xx.com`多个证书，没有对域名做字符大小处理。不会go，只有发issue了。

**Comment by phuslu** [comment]
r244 应该修复了。

**Comment by yoker** [comment]
刚去diff了下。
用户配置文件中的没处理吧，万一用户把配置文件里面域名搞成了大写，好像要悲催了。
按照let's encrpty最新规则，一周限制5次，很快就不能访问了。

**Comment by phuslu** [comment]
呃，我再看看
