### ISSUE TITLE
经常出现这种错误

### ISSUE THREAD

**Issue by hg123** [phuslu/gop#1918]
W0728 23:39:22.327471    8104 handler.go:147] IOCopy &helpers.multiReadCloser{readers:[]io.Reader{(*quic.stream)(0x1116a160), (*autorange.autoPipeReader)(0x120a44d0)}, multiReader:(*io.multiReader)(0x11dc48d0)} return 867909 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)
W0728 23:39:22.327471    8104 handler.go:147] IOCopy &helpers.multiReadCloser{readers:[]io.Reader{(*quic.stream)(0x11dd60b0), (*autorange.autoPipeReader)(0x118c2808)}, multiReader:(*io.multiReader)(0x1275ab20)} return 438544 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)
W0728 23:39:22.327471    8104 handler.go:147] IOCopy &helpers.multiReadCloser{readers:[]io.Reader{(*quic.stream)(0x1115e8f0), (*autorange.autoPipeReader)(0x111144b0)}, multiReader:(*io.multiReader)(0x11fdc020)} return 823606 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)
W0728 23:39:22.327471    8104 handler.go:147] IOCopy &helpers.multiReadCloser{readers:[]io.Reader{(*quic.stream)(0x11dd6420), (*autorange.autoPipeReader)(0x118bbeb0)}, multiReader:(*io.multiReader)(0x11d12d10)} return 339237 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)
W0728 23:39:22.327471    8104 handler.go:147] IOCopy &helpers.multiReadCloser{readers:[]io.Reader{(*quic.stream)(0x1116a210), (*autorange.autoPipeReader)(0x120a5808)}, multiReader:(*io.multiReader)(0x125e0230)} return 313962 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)
W0728 23:39:22.327471    8104 handler.go:147] IOCopy &helpers.multiReadCloser{readers:[]io.Reader{(*quic.stream)(0x11dd6160), (*autorange.autoPipeReader)(0x11115290)}, multiReader:(*io.multiReader)(0x11fddf90)} return 482117 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)
W0728 23:39:22.327471    8104 handler.go:147] IOCopy &helpers.multiReadCloser{readers:[]io.Reader{(*quic.stream)(0x11dd6000), (*autorange.autoPipeReader)(0x11115140)}, multiReader:(*io.multiReader)(0x11fddef0)} return 604692 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)
W0728 23:39:22.327471    8104 handler.go:147] IOCopy &helpers.multiReadCloser{readers:[]io.Reader{(*quic.stream)(0x11dd6210), (*autorange.autoPipeReader)(0x112fc088)}, multiReader:(*io.multiReader)(0x125e1610)} return 233561 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)
W0728 23:39:22.327471    8104 handler.go:147] IOCopy &helpers.multiReadCloser{readers:[]io.Reader{(*quic.stream)(0x11dd62c0), (*autorange.autoPipeReader)(0x111156e8)}, multiReader:(*io.multiReader)(0x11dd46b0)} return 470862 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)
W0728 23:39:22.327471    8104 handler.go:147] IOCopy &helpers.multiReadCloser{readers:[]io.Reader{(*quic.stream)(0x11dd6370), (*autorange.autoPipeReader)(0x120a5db8)}, multiReader:(*io.multiReader)(0x125e1160)} return 260999 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)

修改autorange设置后，有时候是这样

W0728 23:45:43.817298    5148 handler.go:147] IOCopy &quic.stream{mutex:sync.Mutex{state:0, sema:0x0}, streamID:0x9, onData:(func())(0x671830), onReset:(func(protocol.StreamID, protocol.ByteCount))(0x671860), readPosInFrame:1052, writeOffset:0x162, readOffset:0x8ff6, err:(*qerr.QuicError)(0x111b92e0), cancelled:utils.AtomicBool{v:1}, finishedReading:utils.AtomicBool{v:0}, finishedWriting:utils.AtomicBool{v:1}, resetLocally:utils.AtomicBool{v:0}, resetRemotely:utils.AtomicBool{v:0}, frameQueue:(*quic.streamFrameSorter)(0x11e87450), readChan:(chan struct {})(0x112ba440), readDeadline:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, dataForWriting:[]uint8(nil), finSent:utils.AtomicBool{v:1}, rstSent:utils.AtomicBool{v:0}, writeChan:(chan struct {})(0x112ba480), writeDeadline:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, flowControlManager:(*flowcontrol.flowControlManager)(0x1117ab40), laddr:(*net.UDPAddr)(0x11d99c60), raddr:(*net.UDPAddr)(0x11d99c20)} return 36493 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)
W0728 23:45:43.817298    5148 handler.go:147] IOCopy &quic.stream{mutex:sync.Mutex{state:0, sema:0x0}, streamID:0xd, onData:(func())(0x671830), onReset:(func(protocol.StreamID, protocol.ByteCount))(0x671860), readPosInFrame:1051, writeOffset:0x163, readOffset:0x543d3, err:(*qerr.QuicError)(0x111b92e0), cancelled:utils.AtomicBool{v:1}, finishedReading:utils.AtomicBool{v:0}, finishedWriting:utils.AtomicBool{v:1}, resetLocally:utils.AtomicBool{v:0}, resetRemotely:utils.AtomicBool{v:0}, frameQueue:(*quic.streamFrameSorter)(0x11e87460), readChan:(chan struct {})(0x112ba500), readDeadline:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, dataForWriting:[]uint8(nil), finSent:utils.AtomicBool{v:1}, rstSent:utils.AtomicBool{v:0}, writeChan:(chan struct {})(0x112ba540), writeDeadline:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, flowControlManager:(*flowcontrol.flowControlManager)(0x1117ab40), laddr:(*net.UDPAddr)(0x11d99c60), raddr:(*net.UDPAddr)(0x11d99c20)} return 344684 *qerr.QuicError(TooManyOutstandingReceivedPackets: Too many outstanding received packets)

有的时候又是这样

W0728 23:51:10.445461    5976 autorange.go:218] AUTORANGE helpers.IOCopy(&quic.stream{mutex:sync.Mutex{state:0, sema:0x0}, streamID:0x49, onData:(func())(0x671830), onReset:(func(protocol.StreamID, protocol.ByteCount))(0x671860), readPosInFrame:1052, writeOffset:0x176, readOffset:0xc21, err:error(nil), cancelled:utils.AtomicBool{v:0}, finishedReading:utils.AtomicBool{v:0}, finishedWriting:utils.AtomicBool{v:1}, resetLocally:utils.AtomicBool{v:0}, resetRemotely:utils.AtomicBool{v:0}, frameQueue:(*quic.streamFrameSorter)(0x1180ec50), readChan:(chan struct {})(0x11891740), readDeadline:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, dataForWriting:[]uint8(nil), finSent:utils.AtomicBool{v:1}, rstSent:utils.AtomicBool{v:0}, writeChan:(chan struct {})(0x11891780), writeDeadline:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, flowControlManager:(*flowcontrol.flowControlManager)(0x117da0c0), laddr:(*net.UDPAddr)(0x111a20a0), raddr:(*net.UDPAddr)(0x119321e0)}) error: &errors.errorString{s:"io: read/write on closed pipe"}

**Comment by phuslu** [comment]
嗯，quic 的错误正在修复。请安心等待 :)
