### ISSUE TITLE
quic模式是不是太容易被识别了？

### ISSUE THREAD

**Issue by yoker** [phuslu/gop#1922]
vps-r245的服务器和客户端，第一次访问OK的，后面立马就不行了。
![image](https://user-images.githubusercontent.com/444806/28785463-159c2134-7649-11e7-876a-1eb4dee3931a.png)

**Comment by phuslu** [comment]
《依附的自由》

**Comment by masktao** [comment]
quic怎么用?谁有介绍吗?我没用vpn,可以用吗?
