### ISSUE TITLE
关于SSLVerify的问题

### ISSUE THREAD

**Issue by OnionSalt** [phuslu/gop#1927]
https://github.com/phuslu/gop/blob/wiki/ConfigIntroduce.md
看介绍里说SSLVerify要配合GoogleG2KeyID使用，但是gae.json里面没有这个项啊
倒是有个GoogleG2PKP，后面跟着一堆字符串
另外GIAG2.crt这个证书下来以后要安装到什么位置？安装到trusted root下吗？

Google 证书。(Base64编码) 这个是指的GIAG2.crt的base64编码吗？这个要如何得到？

谢谢！

**Comment by MeABc** [comment]
`SSLVerify要配合GoogleG2KeyID使用`  这个是我写给自己看的。。。大家不用纠缠这个。

脚本位置：
[build/ci.sh#L178](https://github.com/phuslu/gop/blob/master/assets/build/ci.sh#L178)

**Comment by MeABc** [comment]
还有这种:

![image](https://user-images.githubusercontent.com/18194126/28895711-0fbb5d10-780c-11e7-8183-a76ea18f94e9.png)

我加入这些的目的有几个：
1. 定位参数出处 ---- 用于验证自己写的对不对。
2. 别人有异议时也可以用这个来讨论我写的对不对或者说我是不是理解错了。

**Comment by SeaHOH** [comment]
由于社长没有单独设置，这个参数还有一个功能就是作为 GAE UrlFetch 的参数，即决定服务端在下载时是否验证证书。
所以开启才对，除非哪天谷歌更换 `GIAG2.crt` 这个中级 CA（估计明年下半年吧，赛门铁克已经投降了）。

**Comment by MeABc** [comment]
感谢提醒！我刚刚更新配置文件。。。现在补上。

**Comment by OnionSalt** [comment]
多谢各位高人回复！
已经开启了
