### ISSUE TITLE
最近的几个版本很烧cpu

### ISSUE THREAD

**Issue by yadex** [phuslu/gop#1930]
![2017-08-09 05-03-57](https://user-images.githubusercontent.com/20081672/29094802-42382df4-7cc1-11e7-86fb-0c93bce9d182.png)

**Comment by phuslu** [comment]
有复现步骤吗，比如按什么步骤访问什么网站可以出现，以及修改了什么默认配置

**Comment by lickety** [comment]
你是什么型号的cpu.
我也是用的最新版本,cpu只占1%.  不连接网络的时候是0%

**Comment by wegood9** [comment]
ARM平台表示cpu占用率和以前差不多

**Comment by qwerttaa** [comment]
快上车k3c，还有机会

我是上了俩k3,

**Comment by yadex** [comment]
找到原因了，不是gop的锅。opera浏览器加载了一个第三方插件。起冲突了，cpu占用奇高。删除插件后，没发现过类似情况。
