### ISSUE TITLE
R1533在路由器上启动成功，但是证书和配置失败？

### ISSUE THREAD

**Issue by ysfuns** [phuslu/gop#1931]
在路由器上安装了mipsle版本的r1533，有两个问题（权限什么的都修改过，以root权限启动程序）

安装过程：下载r1533版本，解压后上传到路由器，然后导入pc上正常可用版本的配置（cache文件夹、GoProxy.key、GoProxy.crt、gae.user.json和httpproxy.user.json），证书不是r1533生成的，是以前的版本生成的，一直都是替换到最新的版本，pc上可用。

1.证书问题
把pc上可行的版本的cache文件夹和GoProxy.key、GoProxy.crt导入到路由器上，没啥效果
2.PC上可用的配置（gae.user.json和httpproxy.user.json），在路由器上不行
pc上100个IP，可用至少60个，在路由器上全显示badip
root@ubnt:/home/ubnt/go# sudo ./goproxy
------------------------------------------------------
GoProxy Version    : r1533 (go/7321a9e11b linux/mipsle)
GoProxy Profile    : Default
Listen Address     : xxxxxxxx:8087
Enabled Filters    : autoproxy,stripssl,autorange|autoproxy,gae,direct|autorange
Pac Server         : http://xxxxxxxxxx:8087/proxy.pac
GAE AppIDs         : xxxxxxx
I0809 13:19:24.002424    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxxxx.appspot.com:443") with good_addrs=0, bad_addrs=0
I0809 13:19:24.195989    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=0
I0809 13:19:24.414712    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=0
I0809 13:19:25.912101    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=0
I0809 13:19:26.865274    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=0
I0809 13:19:27.239891    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=0
I0809 13:19:27.557959    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=0
I0809 13:19:27.685356    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=0
I0809 13:19:28.317885    6103 stripssl.go:158] 121.229.104.183:23574 "STRIP CONNECT fonts.gstatic.com:443 HTTP/1.1" - -
I0809 13:19:28.319663    6103 stripssl.go:158] 121.229.104.183:12869 "STRIP CONNECT www.google.com:443 HTTP/1.1" - -
I0809 13:19:28.321633    6103 stripssl.go:158] 121.229.104.183:16609 "STRIP CONNECT www.google.com.hk:443 HTTP/1.1" - -
I0809 13:19:28.775861    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "www.google.com:443") with good_addrs=0, bad_addrs=0
W0809 13:19:32.044569    6103 gaetransport.go:91] GAE tcp RoundTrip 82.135.118.22 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:32.044981    6103 gaetransport.go:95] GAE: 82.135.118.22 is timeout, add to blacklist for 5m0s
W0809 13:19:32.045520    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-5.appspot.com/_gh/"
I0809 13:19:32.046412    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=12
W0809 13:19:32.205109    6103 gaetransport.go:91] GAE tcp RoundTrip 210.242.125.12 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:32.205368    6103 gaetransport.go:95] GAE: 210.242.125.12 is timeout, add to blacklist for 5m0s
W0809 13:19:32.205600    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-5.appspot.com/_gh/"
I0809 13:19:32.206082    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=23
W0809 13:19:32.424352    6103 gaetransport.go:91] GAE tcp RoundTrip 95.168.222.33 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:32.424726    6103 gaetransport.go:95] GAE: 95.168.222.33 is timeout, add to blacklist for 5m0s
W0809 13:19:32.425158    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-5.appspot.com/_gh/"
I0809 13:19:32.426032    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=32
W0809 13:19:33.921511    6103 gaetransport.go:91] GAE tcp RoundTrip 95.168.222.33 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:33.921878    6103 gaetransport.go:95] GAE: 95.168.222.33 is timeout, add to blacklist for 5m0s
W0809 13:19:33.922324    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-5.appspot.com/_gh/"
I0809 13:19:33.923260    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=40
W0809 13:19:34.875357    6103 gaetransport.go:91] GAE tcp RoundTrip 219.88.189.86 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:34.875736    6103 gaetransport.go:95] GAE: 219.88.189.86 is timeout, add to blacklist for 5m0s
W0809 13:19:34.876156    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-5.appspot.com/_gh/"
I0809 13:19:34.877016    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=48
W0809 13:19:35.249507    6103 gaetransport.go:91] GAE tcp RoundTrip 61.91.9.168 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:35.249884    6103 gaetransport.go:95] GAE: 61.91.9.168 is timeout, add to blacklist for 5m0s
W0809 13:19:35.250318    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-5.appspot.com/_gh/"
I0809 13:19:35.251237    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=52
W0809 13:19:35.612054    6103 gaetransport.go:91] GAE tcp RoundTrip 77.234.91.115 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:35.612436    6103 gaetransport.go:95] GAE: 77.234.91.115 is timeout, add to blacklist for 5m0s
W0809 13:19:35.612870    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-5.appspot.com/_gh/"
I0809 13:19:35.613743    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=57
W0809 13:19:35.695352    6103 gaetransport.go:91] GAE tcp RoundTrip 119.40.97.222 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:35.695733    6103 gaetransport.go:95] GAE: 119.40.97.222 is timeout, add to blacklist for 5m0s
W0809 13:19:35.696277    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-5.appspot.com/_gh/"
I0809 13:19:35.697151    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=61
W0809 13:19:36.786397    6103 gaetransport.go:91] GAE tcp RoundTrip 85.182.250.165 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:36.786772    6103 gaetransport.go:95] GAE: 85.182.250.165 is timeout, add to blacklist for 5m0s
W0809 13:19:36.787255    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://www.google.com/"
I0809 13:19:36.788164    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "www.google.com:443") with good_addrs=0, bad_addrs=64
W0809 13:19:40.058037    6103 gaetransport.go:91] GAE tcp RoundTrip 31.55.166.175 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:40.058410    6103 gaetransport.go:95] GAE: 31.55.166.175 is timeout, add to blacklist for 5m0s
W0809 13:19:40.058888    6103 gaetransport.go:191] GAE: request "http://suggestion.baidu.com/su?wd=https%3A%2F%2Fwww.baidu.com&action=opensearch&ie=UTF-8" error: *net.OpError(dial tcp 31.55.166.175:443: i/o timeout), retry...
I0809 13:19:40.064327    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-9.appspot.com:443") with good_addrs=0, bad_addrs=74
W0809 13:19:40.217798    6103 gaetransport.go:91] GAE tcp RoundTrip 79.101.110.76 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:40.218174    6103 gaetransport.go:95] GAE: 79.101.110.76 is timeout, add to blacklist for 5m0s
W0809 13:19:40.218612    6103 gaetransport.go:191] GAE: request "http://suggestion.baidu.com/su?wd=w&action=opensearch&ie=UTF-8" error: *net.OpError(dial tcp 79.101.110.76:443: i/o timeout), retry...
I0809 13:19:40.223597    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-9.appspot.com:443") with good_addrs=0, bad_addrs=82
W0809 13:19:40.437882    6103 gaetransport.go:91] GAE tcp RoundTrip 83.94.121.244 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:40.438255    6103 gaetransport.go:95] GAE: 83.94.121.244 is timeout, add to blacklist for 5m0s
W0809 13:19:40.438674    6103 gaetransport.go:191] GAE: request "http://suggestion.baidu.com/su?wd=ww&action=opensearch&ie=UTF-8" error: *net.OpError(dial tcp 83.94.121.244:443: i/o timeout), retry...
I0809 13:19:40.444604    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-8.appspot.com:443") with good_addrs=0, bad_addrs=85
W0809 13:19:41.935154    6103 gaetransport.go:91] GAE tcp RoundTrip 212.188.49.222 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:41.935530    6103 gaetransport.go:95] GAE: 212.188.49.222 is timeout, add to blacklist for 5m0s
W0809 13:19:41.935964    6103 gaetransport.go:191] GAE: request "http://suggestion.baidu.com/su?wd=www&action=opensearch&ie=UTF-8" error: *net.OpError(dial tcp 212.188.49.222:443: i/o timeout), retry...
I0809 13:19:41.974567    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-8.appspot.com:443") with good_addrs=0, bad_addrs=89
W0809 13:19:42.889191    6103 gaetransport.go:91] GAE tcp RoundTrip 144.131.80.76 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:42.889603    6103 gaetransport.go:95] GAE: 144.131.80.76 is timeout, add to blacklist for 5m0s
W0809 13:19:42.890128    6103 gaetransport.go:191] GAE: request "http://suggestion.baidu.com/su?wd=www.&action=opensearch&ie=UTF-8" error: *net.OpError(dial tcp 144.131.80.76:443: i/o timeout), retry...
I0809 13:19:42.895852    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=91
W0809 13:19:43.262730    6103 gaetransport.go:91] GAE tcp RoundTrip 2.127.251.174 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:43.263183    6103 gaetransport.go:95] GAE: 2.127.251.174 is timeout, add to blacklist for 5m0s
W0809 13:19:43.263611    6103 gaetransport.go:191] GAE: request "http://suggestion.baidu.com/su?wd=www.g&action=opensearch&ie=UTF-8" error: *net.OpError(dial tcp 2.127.251.174:443: i/o timeout), retry...
I0809 13:19:43.269097    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx.appspot.com:443") with good_addrs=0, bad_addrs=94
I0809 13:19:43.388520    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "clients3.google.com:443") with good_addrs=0, bad_addrs=94
W0809 13:19:43.625857    6103 gaetransport.go:91] GAE tcp RoundTrip 189.247.160.117 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:43.626239    6103 gaetransport.go:95] GAE: 189.247.160.117 is timeout, add to blacklist for 5m0s
W0809 13:19:43.626636    6103 gaetransport.go:191] GAE: request "http://suggestion.baidu.com/su?wd=www.go&action=opensearch&ie=UTF-8" error: *net.OpError(dial tcp 189.247.160.117:443: i/o timeout), retry...
I0809 13:19:43.632500    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=96
W0809 13:19:43.708642    6103 gaetransport.go:91] GAE tcp RoundTrip 188.21.9.244 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:43.709027    6103 gaetransport.go:95] GAE: 188.21.9.244 is timeout, add to blacklist for 5m0s
W0809 13:19:43.709428    6103 gaetransport.go:191] GAE: request "http://suggestion.baidu.com/su?wd=www.goo&action=opensearch&ie=UTF-8" error: *net.OpError(dial tcp 188.21.9.244:443: i/o timeout), retry...
I0809 13:19:43.715505    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-1.appspot.com:443") with good_addrs=0, bad_addrs=98
W0809 13:19:44.799913    6103 gaetransport.go:91] GAE tcp RoundTrip 217.19.150.94 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:44.800253    6103 gaetransport.go:95] GAE: 217.19.150.94 is timeout, add to blacklist for 5m0s
W0809 13:19:44.800580    6103 gae.go:561] 121.229.104.183:12869 "GAE DIRECT GET https://www.google.com/ HTTP/1.1" error: *net.OpError(dial tcp 217.19.150.94:443: i/o timeout)
E0809 13:19:44.800866    6103 handler.go:96] 121.229.104.183:12869 Filter RoundTrip *gae.Filter error: dial tcp 217.19.150.94:443: i/o timeout
W0809 13:19:45.388439    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://clients3.google.com/generate_204"
I0809 13:19:45.388924    6103 gae.go:356] GAE EnableDeadProbe "GET https://clients3.google.com/generate_204" error: context deadline exceeded
I0809 13:19:45.389271    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "clients3.google.com:443") with good_addrs=0, bad_addrs=98
I0809 13:19:47.394105    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "clients3.google.com:443") with good_addrs=0, bad_addrs=98
W0809 13:19:48.076019    6103 gaetransport.go:91] GAE tcp RoundTrip 83.94.121.244 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:48.076398    6103 gaetransport.go:95] GAE: 83.94.121.244 is timeout, add to blacklist for 5m0s
W0809 13:19:48.076823    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-9.appspot.com/_gh/"
I0809 13:19:48.077736    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-9.appspot.com:443") with good_addrs=0, bad_addrs=99
W0809 13:19:48.235306    6103 gaetransport.go:91] GAE tcp RoundTrip 82.77.159.235 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:48.235681    6103 gaetransport.go:95] GAE: 82.77.159.235 is timeout, add to blacklist for 5m0s
W0809 13:19:48.236081    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-9.appspot.com/_gh/"
I0809 13:19:48.236907    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-9.appspot.com:443") with good_addrs=0, bad_addrs=100
W0809 13:19:48.456426    6103 gaetransport.go:91] GAE tcp RoundTrip 1.255.22.121 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:48.456802    6103 gaetransport.go:95] GAE: 1.255.22.121 is timeout, add to blacklist for 5m0s
W0809 13:19:48.457200    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-8.appspot.com/_gh/"
I0809 13:19:48.458029    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-8.appspot.com:443") with good_addrs=0, bad_addrs=100
W0809 13:19:49.394016    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://clients3.google.com/generate_204"
I0809 13:19:49.394784    6103 gae.go:356] GAE EnableDeadProbe "GET https://clients3.google.com/generate_204" error: context deadline exceeded
I0809 13:19:49.395605    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "clients3.google.com:443") with good_addrs=0, bad_addrs=100
W0809 13:19:50.061862    6103 gaetransport.go:91] GAE tcp RoundTrip 217.119.118.106 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:50.062202    6103 gaetransport.go:95] GAE: 217.119.118.106 is timeout, add to blacklist for 5m0s
W0809 13:19:50.062519    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-8.appspot.com/_gh/"
I0809 13:19:50.063294    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-8.appspot.com:443") with good_addrs=0, bad_addrs=100
W0809 13:19:50.907493    6103 gaetransport.go:91] GAE tcp RoundTrip 114.121.194.114 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:50.907829    6103 gaetransport.go:95] GAE: 114.121.194.114 is timeout, add to blacklist for 5m0s
W0809 13:19:50.908171    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-5.appspot.com/_gh/"
I0809 13:19:50.908877    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=100
W0809 13:19:51.280591    6103 gaetransport.go:91] GAE tcp RoundTrip 59.18.45.79 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:51.280931    6103 gaetransport.go:95] GAE: 59.18.45.79 is timeout, add to blacklist for 5m0s
W0809 13:19:51.281283    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx.appspot.com/_gh/"
I0809 13:19:51.281981    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx.appspot.com:443") with good_addrs=0, bad_addrs=100
I0809 13:19:51.400607    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "clients3.google.com:443") with good_addrs=0, bad_addrs=100
W0809 13:19:51.644439    6103 gaetransport.go:91] GAE tcp RoundTrip 77.234.91.38 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:51.644816    6103 gaetransport.go:95] GAE: 77.234.91.38 is timeout, add to blacklist for 5m0s
W0809 13:19:51.645235    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-5.appspot.com/_gh/"
I0809 13:19:51.646120    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-5.appspot.com:443") with good_addrs=0, bad_addrs=100
W0809 13:19:51.727796    6103 gaetransport.go:91] GAE tcp RoundTrip 203.176.178.36 error: &poll.TimeoutError{}, close connection to it
W0809 13:19:51.728187    6103 gaetransport.go:95] GAE: 203.176.178.36 is timeout, add to blacklist for 5m0s
W0809 13:19:51.728574    6103 gaetransport.go:112] GAE *http.Transport.RoundTrip(retry=1) for "https://xxxxxxx-1.appspot.com/_gh/"
I0809 13:19:51.729325    6103 dialer2.go:97] MULTIDIALER DialTLS2("tcp", "xxxxxxx-1.appspot.com:443") with good_addrs=0, bad_addrs=100

xxxxxxx是替换了IP和GAE的ID。

**Comment by MeABc** [comment]
多次重启还是 `good_addrs=0` 吗？

**Comment by ysfuns** [comment]
是的，昨晚开始搭建的，搭建过程重复很多次了，good_addrs=0
这会不会是路由器的防火墙的原因？我已经打开了8087端口啊

**Comment by MeABc** [comment]
防火墙是什么？ iptables ?

**Comment by MeABc** [comment]
如果是 iptables 的话能发一下规则不。

**Comment by ysfuns** [comment]
@MeABc 
不是iptables，但是确实是打开了8087端口，通过公网IP:8087可以访问到
![2](https://user-images.githubusercontent.com/12965256/29108583-341d8baa-7d12-11e7-8059-7593ebbc7ca8.PNG)

**Comment by MeABc** [comment]
呃，这就搞不清楚了。你还有其它 IP 不，换一些 IP 试下。

**Comment by ysfuns** [comment]
@MeABc 
谢谢，搞定，是IP的问题，家里是联通+电信双wan叠加，IP是在电信的网络情况下找到的，不能通用于联通，换了一批在联通网络下找到的IP，是可以的。
