### ISSUE TITLE
问个关于扫IP的问题，ip-range是如何得到的？

### ISSUE THREAD

**Issue by OnionSalt** [phuslu/gop#1936]
ip扫描工具都是依靠ip段，那ip段是怎么得到的？
google的ip段，比如223.255.229.0-223.255.229.255这种段是如何得到？

如果要自己发现新的这种段要怎么弄？

**Comment by MeABc** [comment]
菊苣们写了很多的工具，也回答 N 次这种问题了。搜索 issues 会有答案的。

推荐一个：(这个不是我写的，技术问题不作解答.....)
https://github.com/xyuanmu/checkiptools

你好好研究一个这个。
（此回复是为了消灭 0 回复。）

**Comment by OnionSalt** [comment]
多谢回复，我这就看看去，虽说目前还看不懂....惭愧
