### ISSUE TITLE
goproxy-vps报错，missing certificate

### ISSUE THREAD

**Issue by linhua55** [phuslu/gop#1940]
2017/08/13 01:23:22 http: TLS handshake error from xxx.xxx.182.134:36587: acme/autocert: missing certificate
    2017/08/13 01:23:33 http: TLS handshake error from xxx.xxx.182.134:36607: acme/autocert: missing certificate
    2017/08/13 01:23:33 http: TLS handshake error from xxx.xxx.182.134:36608: acme/autocert: missing certificate
    2017/08/13 01:23:46 http: TLS handshake error from xxx.xxx.182.134:36615: acme: authorization error for xxx.ml: 400 urn:acme:error:connection: Error getting validation data
    2017/08/13 01:23:46 http: TLS handshake error from xxx.xxx.182.134:36623: acme/autocert: missing certificate
    2017/08/13 01:23:52 http: TLS handshake error from xxx.xxx.182.134:36626: acme/autocert: missing certificate

**Comment by phuslu** [comment]
额，删除 ecc/rsa 文件夹，然后重启 goproxy-vps 试试？

**Comment by linhua55** [comment]
没有 ecc/rsa 文件夹

**Comment by phuslu** [comment]
哦，不使用 443 端口没法自动签发证书了，只能自己配置了。
[[http2]]
keyfile = ""
certifle = ""

这种形式。

**Comment by linhua55** [comment]
的确是，端口改为443，就可以了
